services:
  a4_simulator:
    build: .
    container_name: a4-simulation
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - __VK_LAYER_NV_optimus=NVIDIA_only
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
      - __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
    network_mode: host
    volumes:
      - ./scenarios:/root/scenarios # Attach the scenarios folder to the container
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /root/scenarios/illegal_fishing/startup.sh   # Run the startup script
