#!/bin/sh
# @name VRX Rover
# @type Rover
# @class Rover

. ${R}etc/init.d/rc.boat_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=rover}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=wam-v}

param set-default SIM_GZ_EN 1 # Gazebo bridge

# Rover parameters
param set-default GND_L1_DIST 1.0
param set-default GND_L1_PERIOD 1.0
param set-default GND_SP_CTRL_MODE 1
param set-default GND_SPEED_D 0.001
param set-default GND_SPEED_I 8
param set-default GND_SPEED_IMAX 0.125
param set-default GND_SPEED_P 2
param set-default GND_SPEED_THR_SC 1
param set-default GND_SPEED_TRIM 3
param set-default GND_THR_CRUISE 0.85
param set-default GND_THR_MAX 1
param set-default GND_THR_MIN 0

param set-default NAV_ACC_RAD 0.5
param set-default NAV_LOITER_RAD 2

param set-default GND_MAX_ANG 1.57
param set-default GND_WHEEL_BASE 2

param set-default CA_AIRFRAME 9

# Simulated sensors
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 0

# Actuator mapping
param set-default SIM_GZ_SV_FUNC1 101 # right wheel
param set-default SIM_GZ_SV_MIN1 -1000
param set-default SIM_GZ_SV_MAX1 1000
param set-default SIM_GZ_SV_DIS1 0

param set-default SIM_GZ_SV_FUNC2 102 # left wheel
param set-default SIM_GZ_SV_MIN2 -1000
param set-default SIM_GZ_SV_MAX2 1000
param set-default SIM_GZ_SV_DIS2 0


param set-default CA_ROTOR_COUNT 2

param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX -1
param set-default CA_ROTOR0_PY -0.1
param set-default CA_ROTOR0_CT 10

param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX -1
param set-default CA_ROTOR1_PY 0.1
param set-default CA_ROTOR1_CT 10

# param set-default CA_R_REV 3

# param set-default PWM_MAIN_FUNC1 101
# param set-default PWM_MAIN_FUNC2 102
# Steering
# param set-default SIM_GZ_SV_FUNC3 201
# param set-default SIM_GZ_SV_REV 2